name: Game of life CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: node:16

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
